### ISSUE TITLE
Writing async pmtile archives is corrupt

### ISSUE THREAD

**Issue by tristan-morris** [arma-place/pmtiles-rs#10]
Great lib!

I spent a bit of time tracking down what was going on when writing a pmtiles archive with async...

The async gzip writer variant (and I'm assuming the other async compression types), requires `writer.shutdown().await` to be called rather than `writer.flush().await`. This is both in the Directory writing structure and in the metadata writer. 

The sync version isn't impacted.

https://github.com/Nullus157/async-compression/issues/135

**Comment by DerZade** [comment]
Thanks for tracking this down! Sorry for taking a couple of weeks to respond :)

Seems like `shutdown` is quite old and the new way is to call `writer.close().await`. 

<details>
<summary>My (very basics) tests yesterday evening seemed to work with the new code.</summary>

```rs

use pmtiles2::{Compression, PMTiles, TileType};
use tokio::fs::File;
use tokio_util::compat::*;

fn main() -> std::io::Result<()> {
    let mut pm_tiles = PMTiles::new_async(TileType::Png, Compression::GZip);

    pm_tiles.meta_data = Some(serde_json::json!({
        "name": "My PMTiles",
        "description": "This is a description",
        "attribution": "This is an attribution",
        "version": "1.0",
        "format": "pmtiles",
        "type": "baselayer",
        "bounds": [-180.0, -85.05112877980659, 180.0, 85.05112877980659],
        "center": [0.0, 0.0, 2],
        "minzoom": 0,
        "maxzoom": 2,
        "tilejson": "2.2.0",
        "tiles": ["http://localhost:8080/{z}/{x}/{y}.png"]
    }));

    tokio_test::block_on(async {
        let mut file = File::create("foo.pmtiles").await?.compat_write();
        pm_tiles.to_async_writer(&mut file).await?;
        std::io::Result::Ok(())
    })?;

    Ok(())
}

```

</details>


Can you please check if you can reproduce your issue with the [`10-writing-async-pmtile-archives-is-corrupt`-branch](https://github.com/arma-place/pmtiles-rs/tree/10-writing-async-pmtile-archives-is-corrupt)?

_([here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) is a guide how to specify dependencies from a git repo)_
