### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by nyurik** [arma-place/pmtiles-rs#8]
Heads up - https://github.com/stadiamaps/pmtiles-rs/pull/17 -- you might have the same issue -- I tired to run the same test as there and it also failed:

```rust
    #[test]
    fn test_boom() -> Result<()> {
        let bytes: &[u8] = include_bytes!("...../pmtiles-rs/fixtures/tiles.pmtiles");
        let mut reader = Cursor::new(bytes);
        let mut manager = TileManager::new(Some(reader));
        let id = tile_id(7, 35,50);
        assert_eq!(8440, id);
        let tile = manager.get_tile(id);
        let tile = tile.unwrap();
        let tile = tile.unwrap();
        assert_eq!(tile.len(), 100);

        Ok(())
    }
```

(another reason why we really want to join efforts :) )

**Comment by DerZade** [comment]
This is not a bug, seems like your test is just wrong 😅 

The `TileManager` does not work without being configured correctly. You should use a `PMTiles` struct instead.

---

The tile in the PMTiles Viewer:
![chrome_OfyFCwv3SG](https://github.com/arma-place/pmtiles-rs/assets/12705416/cd481091-8687-46fb-820a-f8ba13768bd2)

And this test passes:
```rs
    fn test_from_reader4() -> Result<()> {
        let mut reader = std::fs::File::open("./test/tiles.pmtiles")?;

        let mut pm_tiles = PMTiles::from_reader(&mut reader)?;

        let data= pm_tiles.get_tile(35, 50, 7).unwrap().unwrap();

        assert_eq!(data.len(), 65510);

        Ok(())
    }
```
